# Site settings
title: Aenne Brielmann, Ph.D.
email: aenne.brielmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is the professional homepage of Aenne Brielmann, including some of her art.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//aenneb.github.io" # the base hostname & protocol for your site
twitter_username: aabrielma
github_username:  aenneb

# Build settings
markdown: kramdown
plugins:
  - jekyll-lightgallery
  - jekyll-isotope
  
defaults:
  -
    scope:
      path: "art"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-IMAGES, README.md, bower.json]
